"""add_audit_fields

Revision ID: 07c6c65189d7
Revises: 
Create Date: 2026-05-29 08:44:27.766862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c6c65189d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendario_menu')
    op.drop_table('receta')
    op.drop_table('receta_ingrediente')
    op.drop_table('ingrediente')
    op.drop_table('usuario')
    op.drop_table('categoria_producto')
    op.add_column('calendar_menus', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('calendar_menus', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('calendar_menus', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('calendar_menus', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('calendar_menus', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('calendar_menus', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar_menus', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'calendar_menus', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'calendar_menus', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('ingredients', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('ingredients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('ingredients', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('ingredients', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingredients', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ingredients', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ingredients', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('product_categories', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('product_categories', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('product_categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('product_categories', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('product_categories', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('product_categories', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product_categories', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'product_categories', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'product_categories', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('recipe_ingredients', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('recipe_ingredients', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe_ingredients', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'recipe_ingredients', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'recipe_ingredients', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('recipes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('recipes', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'recipes', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'recipes', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['deleted_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'deleted_by_id')
    op.drop_column('users', 'updated_by_id')
    op.drop_column('users', 'created_by_id')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'deleted_by_id')
    op.drop_column('recipes', 'updated_by_id')
    op.drop_column('recipes', 'created_by_id')
    op.drop_column('recipes', 'deleted_at')
    op.drop_column('recipes', 'updated_at')
    op.drop_column('recipes', 'created_at')
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.drop_constraint(None, 'recipe_ingredients', type_='foreignkey')
    op.drop_column('recipe_ingredients', 'deleted_by_id')
    op.drop_column('recipe_ingredients', 'updated_by_id')
    op.drop_column('recipe_ingredients', 'created_by_id')
    op.drop_column('recipe_ingredients', 'deleted_at')
    op.drop_column('recipe_ingredients', 'updated_at')
    op.drop_column('recipe_ingredients', 'created_at')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_column('product_categories', 'deleted_by_id')
    op.drop_column('product_categories', 'updated_by_id')
    op.drop_column('product_categories', 'created_by_id')
    op.drop_column('product_categories', 'deleted_at')
    op.drop_column('product_categories', 'updated_at')
    op.drop_column('product_categories', 'created_at')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'deleted_by_id')
    op.drop_column('ingredients', 'updated_by_id')
    op.drop_column('ingredients', 'created_by_id')
    op.drop_column('ingredients', 'deleted_at')
    op.drop_column('ingredients', 'updated_at')
    op.drop_column('ingredients', 'created_at')
    op.drop_constraint(None, 'calendar_menus', type_='foreignkey')
    op.drop_constraint(None, 'calendar_menus', type_='foreignkey')
    op.drop_constraint(None, 'calendar_menus', type_='foreignkey')
    op.drop_column('calendar_menus', 'deleted_by_id')
    op.drop_column('calendar_menus', 'updated_by_id')
    op.drop_column('calendar_menus', 'created_by_id')
    op.drop_column('calendar_menus', 'deleted_at')
    op.drop_column('calendar_menus', 'updated_at')
    op.drop_column('calendar_menus', 'created_at')
    op.create_table('categoria_producto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categoria_producto_pkey'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('color_hex', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_pkey'))
    )
    op.create_table('ingrediente',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('es_fresco', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('id_categoria', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria_producto.id'], name=op.f('ingrediente_id_categoria_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingrediente_pkey'))
    )
    op.create_table('receta_ingrediente',
    sa.Column('id_receta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_ingrediente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cantidad_paquetes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_ingrediente'], ['ingrediente.id'], name=op.f('receta_ingrediente_id_ingrediente_fkey')),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id'], name=op.f('receta_ingrediente_id_receta_fkey')),
    sa.PrimaryKeyConstraint('id_receta', 'id_ingrediente', name=op.f('receta_ingrediente_pkey'))
    )
    op.create_table('receta',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('instrucciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('receta_pkey'))
    )
    op.create_table('calendario_menu',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_receta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_comida', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_receta'], ['receta.id'], name=op.f('calendario_menu_id_receta_fkey')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name=op.f('calendario_menu_id_usuario_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('calendario_menu_pkey'))
    )
    # ### end Alembic commands ###
